apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader

helmCharts:
- name: reloader
  releaseName: reloader
  namespace: reloader
  repo: https://stakater.github.io/stakater-charts
  version: 1.0.34
  includeCRDs: true